TaskComplete
mate-academy/ts_group_by_key pull request #1397
Opened 2024-03-12 15:59 UTC by TideTwo

The task itself was easy, but I don't think I will be able to keep up with how convoluting the typing can get, I dread seeing it in an actual complex project instead of just an example task 😅

2024-03-12 16:01 UTC, TideTwo commented
Again issue with Node, prettier and tests. Local check pass proof:
![image](https://github.com/mate-academy/ts_group_by_key/assets/69630160/68fea886-cd1d-45bb-80d5-36e7b8eb714f)

2024-03-14 12:41 UTC, choeqq requested changes

2024-03-14 12:41 UTC, choeqq commented on src/groupByKey.ts
> +export function groupByKey<T>(items: T[], key: string): GroupsMap<T> {
```suggestion
export function groupByKey<T>(items: T[], key: keyof T): GroupsMap<T> {
```

2024-03-14 21:02 UTC, TideTwo commented
Changing type of key parameter makes sense, but I don't see changing ` as keyof GroupsMap<T>` to ` as string` to benefit anything

2024-03-15 08:38 UTC, choeqq approved these changes

2025-01-04 13:07 UTC, closed without merging