Solution
mate-academy/ts_group_by_key pull request #160
Opened 2021-11-24 15:04 UTC by serhii-dvorets

2021-11-25 12:51 UTC, vkryvytskyy requested changes

2021-11-25 12:51 UTC, vkryvytskyy commented on src/groupByKey.ts
> +export function groupByKey(items: any[], key: string): {} {
![image](https://user-images.githubusercontent.com/38065883/143444986-120f97e7-cfae-432b-9a11-7d21eaab489d.png)
Задай правильные типы, не `any` и не `string`

2021-12-06 16:09 UTC, vkryvytskyy requested changes

2021-12-06 16:09 UTC, vkryvytskyy commented on src/groupByKey.ts
> +    result[String(item[key])] = items.filter((obj) => obj[key] === item[key]);
У тебя сейчас на каждом шаге forEach запускается filter, который перебирает весь массив
Давай упростим сложность алгоритма с квадратичной на линейную
Если в result есть ключ для текущего элемента - пушишь текущий элемент в конец этого массива
Если нет - создаешь в резалт по этому ключу массив, и туда кладешь текущий элемент
Тогда не нужно будет запускать filter в forEach

2021-12-07 15:16 UTC, varseniuk approved these changes

2024-05-27 08:43 UTC, closed without merging