Solution
mate-academy/ts_group_by_key pull request #547
Opened 2022-11-11 16:13 UTC by Andriy-Shymkiv

The same task as on mate platform, but with generic using

2022-11-11 17:30 UTC, MaxFedak approved these changes
Good Job)

2022-11-15 10:39 UTC, illiarerun requested changes

2022-11-15 10:39 UTC, illiarerun commented on src/groupByKey.ts
> +export function groupByKey<T>(items: T[], key: string): GroupsMap<T> {
`key` should have a type of possible key from your `T` type

2022-11-15 11:53 UTC, illiarerun approved these changes

2024-03-27 08:30 UTC, closed without merging