Develop ts_group_by_key
mate-academy/ts_group_by_key pull request #753
Opened 2023-03-08 14:05 UTC by sergey-lipikhin

2023-03-08 18:36 UTC, vladyslav-mosor approved these changes
GJ using reduce)

2023-03-09 08:44 UTC, sergii-nosachenko requested changes

2023-03-09 08:44 UTC, sergii-nosachenko commented on src/groupByKey.ts
> +export function groupByKey<T>(items: T[], key: keyof T): object {
The result is not just any object. Use `GroupsMap<T>` instead.

2023-03-09 08:44 UTC, sergii-nosachenko commented on src/groupByKey.ts
> +    const groupKey = singleObject[key] as string;
Avoid type casting. Just convert the value to a string.

2023-03-09 08:44 UTC, sergii-nosachenko commented on src/groupByKey.ts
> +    }
Use advanced techniques:
```suggestion
    groupOfObejcts[groupKey] ??= [];
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment

2023-03-09 08:44 UTC, sergii-nosachenko commented on src/groupByKey.ts
> +  }, {}) as object;
Fix unnecessary type casting.

2023-03-09 10:55 UTC, Yevhenii0536 approved these changes
why did you made so hardreading code? :D try to make simple

2023-03-09 14:37 UTC, OleksiiBlezniuk approved these changes

2024-03-20 11:09 UTC, closed without merging