Group By Key
mate-academy/ts_group_by_key pull request #98
Opened 2021-10-06 08:35 UTC by ivan-major

2021-10-07 09:30 UTC, varseniuk requested changes

2021-10-07 09:30 UTC, varseniuk commented on src/groupByKey.ts
> +    if (i > 0) {
```suggestion
```
Цих двох перевірок не потрібно. В другій перевірці в `else` відбувається все те саме, що і у першій перевірці

2021-10-12 10:06 UTC, ivan-major commented on src/groupByKey.ts
> +    if (i > 0) {
Зробив необхідні зміни, але чомусь не можу повторно відправити на перевірку.

2021-10-22 09:42 UTC, danylo-onishchuk approved these changes
good!

2025-01-26 13:17 UTC, closed without merging